set(CMAKE_Fortran_FLAGS "-fPIC" CACHE STRING "Fortran flag")
set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Flags")
set(Eigen3_DIR "/u/home/a/amit112a/Software/share/eigen3/cmake" CACHE PATH "Eigen")
set(VTK_DIR "/u/home/a/amit112a/Software/lib64/cmake/vtk-8.2" CACHE PATH "VTK")
set(CGAL_DIR "/u/home/a/amit112a/Software/lib64/cmake/CGAL" CACHE PATH "CGAL")
set(BOOST_ROOT "/u/local/apps/boost/1_59_0/gcc-4.4.7/" CACHE PATH "Boost root dir")
